id: I26BBE3DC
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W1KG12678
  ocr_info:
    timestamp: 02/22/24T17:04:58
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-22 11:34:58.674609+00:00
last_modified: 2024-02-22 11:34:58.674613+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12678
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12678
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་ཀྱི་རྒྱལ་པོ་དཔལ་བརྟག་པ་གཉིས་པ།
  languages:
  - bo
  author: སློབ་དཔོན་ག་ཡ་དྷ་ར།
statistics:
  ocr_word_mean_confidence_index: 0.9029187163270087
  ocr_word_median_confidence_index: 0.98
bases:
  I1KG12705:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12705
      total_pages: 66
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12705.txt
    statistics:
      ocr_word_median_confidence_index: 0.98
      ocr_word_mean_confidence_index: 0.9029187163270087
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
